### ISSUE TITLE
Port for GNU Radio 3.8

### ISSUE THREAD

**Issue by devnulling** [MITHaystack/digital_rf#5]
Is there any plans to port gr_digital-rf to support GNU Radio 3.8?

**Comment by ryanvolz** [comment]
New yaml GRC blocks for 3.8+ have been added in 3f54007 which is not yet released. I think that's the only addition needed to support GNU Radio 3.8, but I haven't done any testing yet to confirm that everything works. Once I either do that or hear from someone else (like you!) that it works, I'll put together a release.

**Comment by ryanvolz** [comment]
I just tagged the release, 2.6.3. What I've tested with GNU Radio 3.8 works, but you may have to re-create any gr_digital_rf blocks after converting an existing grc file. Please submit new issues if you run into any problems!
