### ISSUE TITLE
Release tags are not annotated

### ISSUE THREAD

**Issue by imyxh** [MITHaystack/digital_rf#55]
It seems releases since 2.6.3 have not been [annotated](https://git-scm.com/book/en/v2/Git-Basics-Tagging#Annotated-Tags), so when I [package](https://aur.archlinux.org/packages/digital_rf-git) `digital_rf`, the package version (which by convention is taken from `git describe`) is stuck at 2.6.3.

If you could use annotated tags for releases, that'd be great—and more consistent with packaging convention. Thanks for all the work!

**Comment by ryanvolz** [comment]
The `rever` tool that we're using doesn't do annotated tags, but I'm happy to disable that function and do it manually to aid in packaging. Should be good for the latest 2.6.9 release!
